import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main >
        <Image
          className='bg-pattern'
          src="/images/bg-pattern.svg"
          alt="Pattern"
          quality={100}
          fill
          sizes="100vw"
          style={{
            objectFit: 'none',
            objectPosition: 'left top'
          }}
        />
        <section >
          <h1 className='text-darkDesaturatedBlue font-bold text-l'>Simple, traffic-based pricing</h1>
          <p className='text-grayishBlue text-xs'>Sign-up for our 30-day trial.</p>
          <p className='text-grayishBlue text-xs'>No credit card required</p>
        </section>

        <section>
          <p className='text-grayishBlue text-xs font-semibold'>100K PAGEVIEWS</p>
          {/* slider */}
          <div>

          </div>
          <p>$16.00 <span>/ month</span></p>
          <p>Monthly Billing <span></span> Yearly Billing <span>-25%</span></p>
        </section>
        <section>
        <p><Image src="/images/icon-check.svg" className='float-left' width={10} height={10} alt="check" /> Unlimited websites</p>
        <p><Image src="/images/icon-check.svg" width={10} height={10} alt="check" /> 100% data ownership</p>
        <p><Image src="/images/icon-check.svg" width={10} height={10} alt="check" /> Email reports</p>

        <button className='bg-darkDesaturatedBlue rounded-full pb-2 pt-1.5 px-6 text-paleBlue align-text-top'>
          <p className='text-center  '>
            Start my trial
            
            </p>
            </button>
        </section>
      </main>
    </>
  )
}
